import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import villagers from '@/data/villagers.json'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  console.log(villagers)
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <div>
          {
            villagers.map((villager, index) => {
              return (
                <div key={index}>
                  <div> {villager.Name} </div>
                </div>
              )
            })
        }
       </div>
      </main>
    </>
  )
}
